# Generated by Django 5.2.4 on 2026-06-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
