# Generated by Django 5.2.4 on 2026-06-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_created_at_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
